In [1]:
# ! pip install -U spacy -q

In [2]:
!python -m spacy info

zsh:1: command not found: python


In [3]:
# !wget https://raw.githubusercontent.com/amrrs/custom-ner-with-spacy/main/pvr_training_data.json

In [4]:
import spacy
from spacy.tokens import DocBin
from tqdm import tqdm

nlp = spacy.blank("en") # load a new spacy model
db = DocBin() # create a DocBin object

In [5]:
import json
f = open('training_data.json')
TRAIN_DATA = json.load(f)

In [6]:
for text, annot in tqdm(TRAIN_DATA['annotations']): 
    doc = nlp.make_doc(text) 
    ents = []
    for start, end, label in annot["entities"]:
        span = doc.char_span(start, end, label=label, alignment_mode="contract")
        if span is None:
            print("Skipping entity")
        else:
            ents.append(span)
    doc.ents = ents 
    db.add(doc)

db.to_disk("./training_data.spacy") # save the docbin object
db.to_disk("./training_data_maksiti.spacy")
db.to_disk("./training_data_additional.spacy")

100%|██████████| 10/10 [00:00<00:00, 47.66it/s]


In [7]:
! python -m spacy init config config.cfg --lang en --pipeline ner --optimize efficiency

zsh:1: command not found: python


In [8]:
! python -m spacy train config.cfg --output ./ --paths.train ./training_data.spacy --paths.dev ./training_data.spacy
! python -m spacy train config.cfg --output ./ --paths.train ./training_data_maksiti.spacy --paths.dev ./training_data_maksiti.spacy
! python -m spacy train config.cfg --output ./ --paths.train ./training_data_additional.spacy --paths.dev ./training_data_additional.spacy

zsh:1: command not found: python
zsh:1: command not found: python
zsh:1: command not found: python


In [9]:
nlp_ner = spacy.load("/Users/sharailaffendi/Downloads/VSC stuff/MiniProject/custom-ner-with-spacy3/model-best") 

In [2]:
doc = nlp_ner('''55-57, JALAN PEDADA, TAMAN KOTA JAYA, KOTA TINGGI, JOHOR,
JALAN PULAI EMAS 1/4, TAMAN PULAI EMAS, JOHOR BAHRU, NO 11 , JALAN KAKI BUKIT BESERI, PERLIS, 
Lot GF32 & FF31, Waterfront Parkcity, Persiaran Residen, Desapark City, 52200 Kuala Lumpur, 
NO 4&5, DATARAN USAHAWAN, TAMAN SARANG SEMUT, ALOR SETAR, KEDAH
103 & 104, Pasar Taman Samanggah,Jalan Sama Gagah, Taman Samagagah, 13500, Permatang Pauh, Pulau Pinang,
G-43, Citta Mall, No 1, Jalan PJU 1A/48, Ara Damansara, 47301, Petaling Jaya, Selangor''') 

NameError: name 'nlp_ner' is not defined

In [ ]:
spacy.displacy.render(doc, style="ent", jupyter=True) # display in Jupyter

In [ ]:
import numpy
import sklearn.metrics

#Ground-Truth = Address Number, Building Name, Street, PostCode, State, Adress Number
#Predicted = Address Number, Building Name, Street, PostCode, City, Street

#address number 

y_true = ["Positive", "Negative", "Negative", "Negative", "Negative", "Negative", "Positive"]

y_pred = ["Positive", "Negative", "Negative", "Negative", "Negative", "Negative", "Negative"]

r = sklearn.metrics.confusion_matrix(y_true, y_pred)

r = numpy.flip(r)

acc = (r[0][0] + r[-1][-1]) / numpy.sum(r)
print(acc)

0.8571428571428571


In [ ]:
#BuildingName 

#Ground-Truth = Address Number, Building Name, Street, PostCode, State, Adress Number, BuildingName
#Predicted = Address Number, Building Name, Street, PostCode, City, Street, Street

#Building name 

y_true = ["Negative", "Positive", "Negative", "Negative", "Negative", "Negative", "Negative", "Positive"]

y_pred = ["Negative", "Positive", "Negative", "Negative", "Negative", "Negative", "Negative", "Negative"]

r = sklearn.metrics.confusion_matrix(y_true, y_pred)

r = numpy.flip(r)

acc = (r[0][0] + r[-1][-1]) / numpy.sum(r)
print(acc)


0.875


In [ ]:
import sklearn.metrics
import numpy

y_true = ["Red", "Black", "Red",   "White", "White", "Red", "Black", "Red",   "White"]
y_pred = ["Red", "White", "Black", "White", "Red",   "Red", "Black", "White", "Red"]

r = sklearn.metrics.multilabel_confusion_matrix(y_true, y_pred, labels=["White", "Black", "Red"])
print(r)



[[[4 2]
  [2 1]]

 [[6 1]
  [1 1]]

 [[3 2]
  [2 2]]]
